### ISSUE TITLE
Readiness probe based on ClusterSafe influences other nodes

### ISSUE THREAD

**Issue by tobiasdenzler** [hazelcast/hazelcast-openshift#2]
For the readiness probe in OpenShift you propose to use https://github.com/hazelcast/hazelcast-openshift/blob/master/hazelcast-openshift-rhel/readiness.sh, where you check the ClusterSafe information to determine the readiness of a single instance. According to http://docs.hazelcast.org/docs/3.8.6/javadoc/com/hazelcast/core/PartitionService.html#isClusterSafe--, the cluster is safe if "there are no partitions being migrated and all backups are in sync when this method is called".

Imagine a Hazelcast cluster on OpenShift with 3 nodes. If one node goes down, comes back and tries to sync the data, the status of ClusterSafe is false. But that means that all 3 nodes in the cluster are not ready and no connection to the cluster is possible.

Maybe i misunderstand something, but I would not expect that a single node influences the readiness of the others or the whole cluster at all.

**Comment by lazerion** [comment]
@tobiasdenzler Thanks, in documentation we do not propose the `readiness` probe usage, but it is in template deployment, which can be added to documentation as the problem you mentioned. 

Please note that users are free to change deployment and consequently the probes.

When comes to readiness decision for the cluster, @noctarius is the guy. @noctarius could you please advise for changes, if required.

**Comment by noctarius** [comment]
@tobiasdenzler it is actually true, that the whole cluster is in an unsafe state when a node leaves or joins. This is because of the fact that partition migrations happen and new backups need to be created. I'm not sure but I think your problem is, that a potential Hazelcast client based application won't connect because the cluster is not "ready"? Did I get this correct?

**Comment by tobiasdenzler** [comment]
@noctarius The problem in our case is how OpenShift reacts to the readiness probe. As soon as the readiness probe returns false, OpenShift will remove the Hazelcast instance from the service loadbalancer and no new requests will reach that instance. This might be the correct behavior for a single node, but the state of unsafe cluster reflects to all instances in the cluster. That leads to the situation, where no Hazelcast instance is ready to accept connections/requests and the cluster is down as soon as you have the "unsafe cluster" state.

**Comment by noctarius** [comment]
You're using the load balancer to connect to the Hazelcast cluster?

**Comment by tobiasdenzler** [comment]
Yes, we are using the service in OpenShift to connect to the cluster.

**Comment by tobiasdenzler** [comment]
We use the service to abstract the multiple Hazelcast nodes in OpenShift. There is 1 service with a fix hostname and n instances of Hazelcast pods behind with volatile IPs. The HZ instances are using the Kubernetes discovery plugin the form the cluster. The client the connects to the cluster using the hostname of the service.

What you propose is to use the discovery plugin also for connecting the clients to the cluster? Do I get this right? Never looked at it this way ;-)..

But then the readiness check has a more informal character as there is no impact to the cluster/node in case of a "not ready" instance?

**Comment by tobiasdenzler** [comment]
Ok, now I am a bit confused. To my understanding the Kubernetes discovery plugin uses the Kubernetes/OpenShift service to get the IPs of the Hazelcast nodes. 

_This Hazelcast Discovery Plugin provides the possibility to lookup IP addresses of other members by resolving those requests against a Kubernetes Service Discovery system._

So if a node is not ready due to the readiness.sh script, Kubernetes will remove it from the service and the discovery plugin will not be abler to connect to that node again. Or am I wrong?

**Comment by googlielmo** [comment]
Hi @tobiasdenzler I'm closing this as this PR: https://github.com/hazelcast/hazelcast-kubernetes/pull/57 introduced the option for a pod that is not ready to join the cluster, which I think solves your original issue. Feel free to reopen this or create a new issue if that's not the case.
