### ISSUE TITLE
Move hazelcast/hazelcast-openshift to hazelcast/hazelcast-docker repo

### ISSUE THREAD

**Issue by leszko** [hazelcast/hazelcast-openshift#39]
We don't need a separate repository for the Red Hat certified Docker image. I suggest moving it into [hazelcast/hazelcast-docker](https://github.com/hazelcast/hazelcast-docker).

**Comment by hasancelik** [comment]
I think we also do not need separate docker image for openshift envs, we can replace existing [hazelcast/hazelcast-enterprise](https://github.com/hazelcast/hazelcast-docker/tree/master/hazelcast-enterprise) which is `alpine based` with this one which is `rhel-based`. `RHEL` is more secure/enterprise than alpine, only cons is image size increase as far as i recall. We have already discussed it with @kwart at another issue or e-mail thread that I could not find 🙂

**Comment by leszko** [comment]
Yeah, We could merge them. The only drawback I see is the image size. Not sure how big the issue is for enterprise customers.
