### ISSUE TITLE
Use 'secret' for enterprise license key for RHEL based image

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast-openshift#6]
Documentation can be found:
https://docs.openshift.com/container-platform/3.5/dev_guide/secrets.html

**Comment by leszko** [comment]
@lazerion 

In this repository we plan to keep only the source for Docker images (Dockerfiles + some scripts), but not the templates. Templates are just samples and will be moved to code samples.

Taking that into consideration, at the Docker image level, it's not possible to inject OpenShift Secrets. WDYT?

**Comment by mesutcelik** [comment]
added here as req 1.
https://hazelcast.atlassian.net/wiki/spaces/PM/pages/147652637/Openshift+Enterprise+Security+Verification
