### ISSUE TITLE
Liveness Probe populate log with many messages

### ISSUE THREAD

**Issue by dips276** [hazelcast/hazelcast-openshift#7]
Hi 

I've just added the liveness probe to my Hazelcast processes on Openshiftm and now i see the following messages in my logs - every 10 seconds:

> Jan 10 2018 15:19:29:833 UTC - [hz.hazelcast-imdg-os-test-13-s9vcz.IO.thread-Acceptor] - INFO - com.hazelcast.nio.tcp.TcpIpAcceptor$AcceptorIOThread.acceptSocket - [192.168.12.190]:5701 [local-cluster] [3.9.2] Accepting socket connection from /192.168.12.190:41586
Jan 10 2018 15:19:29:838 UTC - [hz.hazelcast-imdg-os-test-13-s9vcz.cached.thread-1] - INFO - com.hazelcast.nio.tcp.TcpIpConnectionManager.newConnection - [192.168.12.190]:5701 [local-cluster] [3.9.2] Established socket connection between /192.168.12.190:5701 and /192.168.12.190:41586
Jan 10 2018 15:19:29:843 UTC - [hz.hazelcast-imdg-os-test-13-s9vcz.IO.thread-in-2] - INFO - com.hazelcast.nio.tcp.TcpIpConnection.close - [192.168.12.190]:5701 [local-cluster] [3.9.2] Connection[id=24, /192.168.12.190:5701->/192.168.12.190:41586, endpoint=null, alive=false, type=REST_CLIENT] closed. Reason: Connection closed by the other side
Jan 10 2018 15:19:30:052 UTC - [hz.hazelcast-imdg-os-test-13-s9vcz.IO.thread-Acceptor] - INFO - com.hazelcast.nio.tcp.TcpIpAcceptor$AcceptorIOThread.acceptSocket - [192.168.12.190]:5701 [local-cluster] [3.9.2] Accepting socket connection from /192.168.12.190:41602
Jan 10 2018 15:19:30:053 UTC - [hz.hazelcast-imdg-os-test-13-s9vcz.cached.thread-1] - INFO - com.hazelcast.nio.tcp.TcpIpConnectionManager.newConnection - [192.168.12.190]:5701 [local-cluster] [3.9.2] Established socket connection between /192.168.12.190:5701 and /192.168.12.190:41602
Jan 10 2018 15:19:30:056 UTC - [hz.hazelcast-imdg-os-test-13-s9vcz.IO.thread-in-0] - INFO - com.hazelcast.nio.tcp.TcpIpConnection.close - [192.168.12.190]:5701 [local-cluster] [3.9.2] Connection[id=25, /192.168.12.190:5701->/192.168.12.190:41602, endpoint=null, alive=false, type=REST_CLIENT] closed. Reason: Connection closed by the other side

Can we mute this log? Or somehow stop Hazelcast filling up the log like this due to the healthcheck?

Dipesh

**Comment by dbrimley** [comment]
@googlielmo Could we look at muting this please and getting a release out?

**Comment by hasancelik** [comment]
similar to https://github.com/hazelcast/hazelcast-docker/issues/52

**Comment by shahbour** [comment]
Any plan for releasing a version that mute this?

**Comment by googlielmo** [comment]
A workaround at the moment is to specify a custom logging configuration to mute those packages.
Please follow https://github.com/hazelcast/hazelcast/issues/12687

**Comment by leszko** [comment]
This logging is included in Hazelcast Core and it won't be changed, since it's useful in many cases.

Closing as "won't fix". Please use the workaround.
