### ISSUE TITLE
Wrong image mentioned in the hazelcast-template.json

### ISSUE THREAD

**Issue by anupfrancis** [hazelcast/hazelcast-openshift#8]
In hazelcast-template.json, wrong value given for image. https://raw.githubusercontent.com/hazelcast/hazelcast-openshift/master/hazelcast-openshift-origin/hazelcast-template.json
"spec": {
            "containers": [
              {
                "image": "hazelcast/hazelcast-openshift-orgin:${HAZELCAST_VERSION}",
                
It needs to be 
                "image": "hazelcast/hazelcast-openshift:${HAZELCAST_VERSION}",

**Comment by hasancelik** [comment]
@anupfrancis , Thanks for your report 👍  We will fix it ASAP.
